# Generated by Django 3.2 on 2021-10-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0001_initial'),
        ('keaNet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keanet',
            name='cellphone',
        ),
        migrations.AddField(
            model_name='keanet',
            name='cellphone',
            field=models.ManyToManyField(to='cellphone.cellphone'),
        ),
    ]
