# Generated by Django 3.2 on 2021-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keaNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keanet',
            name='totalPrice',
            field=models.FloatField(blank=True),
        ),
    ]
